$pdf_mode = 1;
set_tex_cmds('-interaction=nonstopmode %O %S');

my $moreopts = '';
$moreopts .= ',handout' unless $ENV{'NH'};

open(my $fh, '>', 'class.tex') or die "Could not open file: $!";
print $fh "\\documentclass[xcolor=dvipsnames,aspectratio=169${moreopts}]{beamer}\n";
close($fh);
